services:
  meshwave:
    image: meshwave
    build:
      context: .
      dockerfile: Meshwave/Dockerfile
    ports:
      - 3333:8080
    networks:
      - meshwave_network
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - meshwave_network
    command: redis-server --appendonly yes
    volumes:
      - meshwave_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  meshwave_network:
    driver: bridge

volumes:
  meshwave_data: